activity:
  beginning:
    create: 'Beginning has been created'
    update: 'Someone has edited a beginning'
    destroy: 'Some user removed a beginning!'

  ending:
    create: 'Ending has been created'
    update: 'Someone has edited an ending'
    destroy: 'Some user removed a ending!'

  comment:
    create: 'Comment has been created'
    update: 'Someone has edited a comment'
    destroy: 'Some user removed a comment!'

